# Generated by Django 5.0.3 on 2024-06-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('num_star', models.IntegerField(choices=[(1, 'Wrost'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.musician')),
            ],
        ),
    ]
